### ISSUE TITLE
Demo - login (nodejs)

### ISSUE THREAD

**Issue by zoltanhalasz** [TypingDNA/Demos#3]
Login demo, for nodejs.

After npm install and inserting my api key and apiSecret, I start the application, navigate to localhost:3000 and enter a valid email address and a madeup password.
Error message: "Error verifying user."
What am I missing?

**Comment by adrianpoacatypingdna** [comment]
Hi Zoltan,

Thank you for bringing this to our attention. 

We have made some changes in our subscription models and the new free developer account only has access to the AUTO API call. The demo presented here is using the VERIFY and SAVE API calls that are only available from the PRO account.

We are expecting to publish new demos that are using the AUTO API call in a matter of days. We will let you know as soon as the new version are published.

Thank you,
Adrian

**Comment by adrianpoacatypingdna** [comment]
Hi Zoltan,

We have made the updated to our demos and they now support the subscription that you have.

Feel free to use the latest code and let us know if you have any other questions.

Thank you,
Adrian
